version: '3'
services:
  jenkins:
    build:
      context: jenkins/
    container_name: jenkins
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
       - ./svc_jenkins:/svc_jenkins
       - /data:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
       - /etc/localtime:/etc/localtime
